server:
  applicationConnectors:
    - type: http
      port: 8090

dbInsider:
  uri: "mongodb://localhost:27017/insider_program?readPreference=secondaryPreferred"

dbSession:
  uri: "mongodb://localhost:27017/insider_sessions?readPreference=secondaryPreferred"

api:
  cors:
    allowedOrigins: "http://localhost:*,https://example.domain"
    allowedHeaders: "Authorization,X-Requested-With,X-Txn-Auth-Token,Content-Type,Accept,Origin"
